#!/bin/sh

#
# Applications
#

# emacs
bspc rule -a Emacs state=tiled

#
# General
#

# polybar
~/.config/polybar/launch.sh

# background
xwallpaper --zoom ~/.config/wallpaper.png

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# picom
picom --config ~/.config/picom/picom.conf

bspc config border_width 2

